{% set name = "fates-emerald" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/NordicESMHub/ctsm/archive/release-emerald{{ version }}.tar.gz
    sha256: 5a1e2c0a8189403af82ff5cc7fc8214c6d1188781d792438b2d280b49f0ffff1

build:
    skip: True  # [win or osx]
    number: 1

requirements:
    build:
        - {{ compiler('c') }}
        - cmake
    host:
        - python >=3
        - mpich
        - hdf5
        - netcdf-fortran
        - svn
    run:
        - tcsh
        - python >=3
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - netcdf-fortran
        - mpich
        - libxml2
        - perl-xml-libxml
        - libiconv
        - make
        - cmake
        - mkl
        - wget

test:
    commands:
        - create_newcase --help
        - create_clone --help
        - query_testlists --help
        - query_config --help

about:
    home: https://github.com/NordicESMhub/ctsm/tree/fates_emerald_api
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: The EMERALD version of the Functionally Assembled Terrestrial Ecosystem Simulator (FATES) with Community Terrestrial Systems Model as host model is maintained by the University of Oslo. In this version FATES can be run on a number of pre-defined sites (in the Nordic regions) where in-situ observations are collected.
    doc_url: https://github.com/NordicESMhub/ctsm/blob/fates_emerald_api/README_fates_emerald_api

extra:
  recipe-maintainers:
    - annefou
  skip-lints:
    - compilers_must_be_in_build
