package:
  name: nextflow
  version: "0.23.4"

build:
  number: 0

source:
  fn: nextflow
  url: https://github.com/nextflow-io/nextflow/releases/download/v0.23.4/nextflow
  md5: ace2aebfc7b18be1f4605ff803ccbc9c

requirements:
  run:
    - java-jdk >=7.0
    - coreutils

test:
  commands:
    - nextflow -v

about:
  home: "https://github.com/nextflow-io/nextflow"
  license: "GPL3"
  summary: "A DSL for data-driven computational pipelines http://nextflow.io"
