package:
  name: ddocent
  version: '2.2.15'
source:
  fn: v2.2.15.zip
  sha256: 5d8eb75e5290bcd4080b7b3e9f778bcd182b0ea7d3b6063b0d4efaf190bedce2
  url: https://github.com/jpuritz/dDocent/archive/v2.2.15.zip
build:
  number: 0
  skip: True # [osx]
requirements:
  build:
    - gcc #  [unix]
    - curl
    - cmake
    - freebayes
    - gawk
    - stacks
    - trimmomatic
    - mawk
    - bwa
    - samtools 
    - vcftools ==0.1.14
    - rainbow
    - seqtk
    - cd-hit
    - bedtools ==2.26.0
    - vcflib
    - gnuplot
    - parallel
    - bamtools
    - openjdk
    - pear
    - unzip
  run:
    - libgcc # [unix]
    - curl
    - cmake
    - freebayes
    - gawk
    - stacks
    - trimmomatic
    - mawk
    - bwa
    - samtools
    - vcftools ==0.1.14
    - rainbow
    - seqtk
    - cd-hit
    - bedtools ==2.26.0
    - vcflib
    - gnuplot
    - parallel
    - bamtools
    - openjdk
    - pear
    - unzip
    
test:
    commands:
        - "dDocent --help"
about:
    home: "http://ddocent.wordpress.com/"
    license: "The MIT License (MIT)"
    summary: " dDocent is  an interactive bash wrapper to QC, assemble, map, and call SNPs from double digest RAD data"

